

#ifndef __PRINTHELLOWORLD_H__
#define __PRINTHELLOWORLD_H__

#define EFI_PRINTHELLOWORLD_PROTOCOL_GUID  \
	{0xf9954a52, 0x986e, 0x41b9, {0xb5,0x1b,0xe7,0x49,0xa1,0x93,0xef,0xa1}}

typedef 
EFI_STATUS
(EFIAPI *PRINT_HELLO_WORLD)(BOOLEAN);

typedef
struct _EFI_PRINTHELLOWORLD_PROTOCOL {
	PRINT_HELLO_WORLD PrintHelloWorld;
}EFI_PRINTHELLOWORLD_PROTOCOL;

EFI_GUID gEfiPrintHelloWorldProtocolGuid = EFI_PRINTHELLOWORLD_PROTOCOL_GUID;

#endif